"""rename picture to avatar_url

Revision ID: 0950be30c72b
Revises: ccc2da40b6bf
Create Date: 2025-06-22 05:17:25.445680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0950be30c72b'
down_revision: Union[str, None] = 'ccc2da40b6bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'picture', new_column_name='avatar_url', existing_type=sa.String())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_url', new_column_name='picture', existing_type=sa.String())
    # ### end Alembic commands ###
