name: skatespot
version: '3.9'

services:
  postgres:
    image: postgis/postgis:15-3.4
    environment:
      - POSTGRES_USER=skateuser
      - POSTGRES_PASSWORD=skatepassword
      - POSTGRES_DB=skatespot
    env_file:
      - ./env/.env.local
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    container_name: skatespot-postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U skateuser -d skatespot']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: skatespot-backend
    build:
      context: ../backend_py
      dockerfile: Dockerfile
    # volumes:
    #   - ../backend_py:/app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./env/.env.local
    ports:
      - '3000:3000'
    container_name: skatespot-backend

  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    volumes:
      - ../frontend:/app/frontend
    depends_on:
      - backend
    ports:
      - '5173:5173'
    container_name: skatespot-frontend
    command: pnpm run dev --host

volumes:
  pgdata:
