name: Quick Tests

on:
  push:
    paths:
      - 'backend_py/**'
      - '.github/workflows/quick-test.yml'
  pull_request:
    paths:
      - 'backend_py/**'

jobs:
  backend-unit-tests:
    name: Quick Backend Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend_py/requirements.txt

      - name: Install dependencies
        run: |
          cd backend_py
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        env:
          DATABASE_URL: sqlite+aiosqlite:///:memory:
          JWT_SECRET_KEY: test-secret-key
          GOOGLE_CLIENT_ID: test-client-id
          GOOGLE_CLIENT_SECRET: test-client-secret
        run: |
          cd backend_py
          python -m pytest tests/ -v --tb=short -x